// The one definition of a conventional subject line, shared by the
// `commit-msg` hook (hooks/commit-msg.ts) and the pull request title check
// (pr/title-command.ts). A squash merge turns the pull request title into the
// commit on `main`, so both must accept exactly the same thing; keeping the
// rule here means they cannot drift apart.

export const ALLOWED_PREFIXES = ["feat", "fix", "docs", "chore"] as const;

const EXAMPLE = "fix(gate): count lines in files without a final newline";

// prefix, optional non-empty scope in parentheses, a colon and one space, then
// a subject that starts with something visible.
const CONVENTIONAL = new RegExp(
  `^(?:${ALLOWED_PREFIXES.join("|")})(?:\\([^()\\s][^()]*\\))?: \\S`,
);

// Subjects git writes itself. Nobody typed them, so the rule can't ask them to
// be rewritten. `fixup!`, `squash!` and `amend!` are temporary: an
// autosquash rebase folds them into the commit they name. "Initial commit",
// exactly, is the near-universal first commit (GitHub writes it when it
// creates a repo with a README, and setup uses it), so it's accepted too.
const GIT_GENERATED = [
  /^Merge /,
  /^Revert "/,
  /^(?:fixup|squash|amend)! /,
  /^Initial commit$/,
];

/** True when `subject` is `<prefix>(<scope>): <text>` with an allowed prefix. */
export function isConventionalSubject(subject: string): boolean {
  return CONVENTIONAL.test(subject);
}

/**
 * The subject of a commit message file, or undefined when there is none.
 * Comment lines (the `#` help text git adds in the editor) and blank lines
 * before the subject don't count.
 */
export function commitSubject(message: string): string | undefined {
  for (const line of message.split(/\r?\n/)) {
    if (line.startsWith("#") || line.trim() === "") {
      continue;
    }
    return line;
  }
  return undefined;
}

/**
 * A commit message passes when its subject is conventional, was generated by
 * git (merge, revert, rebase markers), or is missing: git itself refuses an
 * empty message unless the author asked for one with --allow-empty-message.
 */
export function isAcceptableCommitMessage(message: string): boolean {
  const subject = commitSubject(message);
  return (
    subject === undefined ||
    isConventionalSubject(subject) ||
    GIT_GENERATED.some((pattern) => pattern.test(subject))
  );
}

/** What both checks print for a bad subject: the rule, then an example. */
export function describeRefusal(subject: string, what: string): string {
  const shown = subject === "" ? "(empty)" : subject;
  return [
    `temple-bar: ${what} needs a conventional prefix: ${shown}`,
    `  Start with ${ALLOWED_PREFIXES.join(", ")}, an optional (scope), a colon and a space, then the subject.`,
    `  Example: ${EXAMPLE}`,
    "",
  ].join("\n");
}
